import asyncio
from motor.motor_asyncio import AsyncIOMotorClient
import os
from dotenv import load_dotenv
from pathlib import Path

ROOT_DIR = Path(__file__).parent
load_dotenv(ROOT_DIR / '.env')

mongo_url = os.environ['MONGO_URL']
client = AsyncIOMotorClient(mongo_url)
db = client[os.environ['DB_NAME']]

# Tamil Questions Data
tamil_questions = [
    {"id": "tamil_1", "question_number": 1, "question_text": "'அவன் பொன்னன்' என்பதில் 'பொன்னன்' எவ்வகைப் பெயர்?", "options": [{"label": "A", "text": "பொருட் பெயர்"}, {"label": "B", "text": "இடப் பெயர்"}, {"label": "C", "text": "காலப் பெயர்"}, {"label": "D", "text": "தொழில் பெயர்"}], "correct_answer": "A", "marks": 2, "subject": "tamil", "part": "A"},
    {"id": "tamil_2", "question_number": 2, "question_text": "எட்டுத்தொகை நூல்களுள் முதலாவதாக வைத்து எண்ணப்படும் நூல்?", "options": [{"label": "A", "text": "அகநானூறு"}, {"label": "B", "text": "ஐங்குறுநூறு"}, {"label": "C", "text": "நற்றினை"}, {"label": "D", "text": "பரிபாடல்"}], "correct_answer": "C", "marks": 2, "subject": "tamil", "part": "A"},
    {"id": "tamil_3", "question_number": 3, "question_text": "ஆரிய அரசன் பிரகத்தனுக்கு தமிழ் அறிவுறுத்த எழுதப்பட்ட நூல் எது?", "options": [{"label": "A", "text": "பட்டினப்பாலை"}, {"label": "B", "text": "முல்லைப்பாட்டு"}, {"label": "C", "text": "திருக்குறள்"}, {"label": "D", "text": "குறிஞ்சிப்பாட்டு"}], "correct_answer": "D", "marks": 2, "subject": "tamil", "part": "A"},
    {"id": "tamil_4", "question_number": 4, "question_text": "'பொங்கல் உண்டான்' என்பதில் 'உண்டான்' எவ்வகைப் பெயர்?", "options": [{"label": "A", "text": "பண்பாகு பெயர்"}, {"label": "B", "text": "முதலாகு பெயர்"}, {"label": "C", "text": "இடவாகு பெயர்"}, {"label": "D", "text": "தொழிலாகு பெயர்"}], "correct_answer": "D", "marks": 2, "subject": "tamil", "part": "A"},
    {"id": "tamil_5", "question_number": 5, "question_text": "ஏலாதியின் ஆசிரியர் யார்?", "options": [{"label": "A", "text": "கணிமேதாவியார்"}, {"label": "B", "text": "காரியாசான்"}, {"label": "C", "text": "விளம்பிநாகனார்"}, {"label": "D", "text": "பூதஞ்சேந்தனார்"}], "correct_answer": "A", "marks": 2, "subject": "tamil", "part": "A"},
    {"id": "tamil_6", "question_number": 6, "question_text": "வெட்சித்திணை என்பது யாது?", "options": [{"label": "A", "text": "நிரை கவர்தல்"}, {"label": "B", "text": "மதிலை வளைத்தல்"}, {"label": "C", "text": "நிரை மீட்டல்"}, {"label": "D", "text": "மதில் காத்தல்"}], "correct_answer": "A", "marks": 2, "subject": "tamil", "part": "A"},
    {"id": "tamil_7", "question_number": 7, "question_text": "கண்ணதாசன் இறுதிக் காலத்தில் எழுதிய காவியம் எது?", "options": [{"label": "A", "text": "உதயண காவியம்"}, {"label": "B", "text": "இயேசு காவியம்"}, {"label": "C", "text": "யசோதர காவியம்"}, {"label": "D", "text": "இயேசுமா காவியம்"}], "correct_answer": "B", "marks": 2, "subject": "tamil", "part": "A"},
    {"id": "tamil_8", "question_number": 8, "question_text": "'உவமைக் கவிஞர்' என்ற விருதைப் பெற்றவர் யார்?", "options": [{"label": "A", "text": "சுரதா"}, {"label": "B", "text": "முடியரசன்"}, {"label": "C", "text": "நாமக்கல்லார்"}, {"label": "D", "text": "வாணிதாசன்"}], "correct_answer": "A", "marks": 2, "subject": "tamil", "part": "A"},
    {"id": "tamil_9", "question_number": 9, "question_text": "கல்வெட்டுகளில் காணப்படும் எழுத்து வகைகள் எத்தனை?", "options": [{"label": "A", "text": "2"}, {"label": "B", "text": "3"}, {"label": "C", "text": "5"}, {"label": "D", "text": "4"}], "correct_answer": "B", "marks": 2, "subject": "tamil", "part": "A"},
    {"id": "tamil_10", "question_number": 10, "question_text": "எற்பாடு என்பது எது?", "options": [{"label": "A", "text": "பிரிதலும் பிரிதல் நிமித்தமும்"}, {"label": "B", "text": "முன்பனிக் காலம்"}, {"label": "C", "text": "ஞாயிறு மறையும் நேரம்"}, {"label": "D", "text": "காலை 6 மணி முதல் 10 மணி வரை"}], "correct_answer": "C", "marks": 2, "subject": "tamil", "part": "A"},
    {"id": "tamil_11", "question_number": 11, "question_text": "தமிழ் நாட்டில் வடமொழியை எழுதுவதற்குப் பயன்படுத்தப்பட்ட மொழி?", "options": [{"label": "A", "text": "கிரந்தம்"}, {"label": "B", "text": "வட்டெழுத்து"}, {"label": "C", "text": "பிராமி"}, {"label": "D", "text": "சமஸ்கிருதம்"}], "correct_answer": "A", "marks": 2, "subject": "tamil", "part": "A"},
    {"id": "tamil_12", "question_number": 12, "question_text": "'வானம் வசப்படும்' என்ற பிரபஞ்சனின் படைப்பு?", "options": [{"label": "A", "text": "கவிதை நூல்"}, {"label": "B", "text": "வரலாற்றுப் புதினம்"}, {"label": "C", "text": "சிறுகதைத் தொகுப்பு"}, {"label": "D", "text": "சூழலியல் கட்டுரை"}], "correct_answer": "B", "marks": 2, "subject": "tamil", "part": "A"},
    {"id": "tamil_13", "question_number": 13, "question_text": "இலையின் பெயரைக் குறிக்காத சொல்லைத் தேர்ந்தெடுக்கவும்:", "options": [{"label": "A", "text": "தாள்"}, {"label": "B", "text": "கழை"}, {"label": "C", "text": "ஓலை"}, {"label": "D", "text": "தோகை"}], "correct_answer": "B", "marks": 2, "subject": "tamil", "part": "A"},
    {"id": "tamil_14", "question_number": 14, "question_text": "இந்தியாவில் முதல் முதலாக வானொலி ஒளிபரப்பு தொடங்கப்பட்ட இடம் எது?", "options": [{"label": "A", "text": "கல்கத்தா"}, {"label": "B", "text": "நியூடெல்லி"}, {"label": "C", "text": "மும்பை"}, {"label": "D", "text": "சென்னை"}], "correct_answer": "D", "marks": 2, "subject": "tamil", "part": "A"},
    {"id": "tamil_15", "question_number": 15, "question_text": "தமிழில் வெளியான முதல் திங்கள் இதழ் எது?", "options": [{"label": "A", "text": "சுதேச மித்திரன்"}, {"label": "B", "text": "தமிழ்ப் பத்திரிகா"}, {"label": "C", "text": "தின மணி"}, {"label": "D", "text": "தினசரி"}], "correct_answer": "A", "marks": 2, "subject": "tamil", "part": "A"},
    {"id": "tamil_16", "question_number": 16, "question_text": "குறுந்தொகைப் பாடல்களில் அடி வரையறை?", "options": [{"label": "A", "text": "4 – 8"}, {"label": "B", "text": "9 – 12"}, {"label": "C", "text": "7 – 13"}, {"label": "D", "text": "13 – 31"}], "correct_answer": "A", "marks": 2, "subject": "tamil", "part": "A"},
    {"id": "tamil_17", "question_number": 17, "question_text": "'நெடுந்தொகை' என அழைக்கப்படும் நூல் எது?", "options": [{"label": "A", "text": "அகனானூறு"}, {"label": "B", "text": "புறநானூறு"}, {"label": "C", "text": "குறுந்தொகை"}, {"label": "D", "text": "நற்றிணை"}], "correct_answer": "A", "marks": 2, "subject": "tamil", "part": "A"},
    {"id": "tamil_18", "question_number": 18, "question_text": "செல்வச் செல்வி - இலக்கணக் குறிப்பு", "options": [{"label": "A", "text": "அடுக்குத் தொடர்"}, {"label": "B", "text": "உவமை"}, {"label": "C", "text": "எண்ணும்மை"}, {"label": "D", "text": "உருவகம்"}], "correct_answer": "D", "marks": 2, "subject": "tamil", "part": "A"},
    {"id": "tamil_19", "question_number": 19, "question_text": "சிலப்பதிகாரம் இவர் முன்னிலையில் அரங்கேற்றப்பட்டது — அந்த நபர் யார்?", "options": [{"label": "A", "text": "பாண்டியன் நெடுஞ்செழியன்"}, {"label": "B", "text": "பனன்பாரனார்"}, {"label": "C", "text": "அடியார்க்குநல்லார்"}, {"label": "D", "text": "சாத்தனார்"}], "correct_answer": "D", "marks": 2, "subject": "tamil", "part": "A"},
    {"id": "tamil_20", "question_number": 20, "question_text": "'அவை அஞ்சா' - இது எவ்வகை?", "options": [{"label": "A", "text": "அகத்திணை"}, {"label": "B", "text": "புறத்திணை"}, {"label": "C", "text": "அரசனைப் பாடுதல்"}, {"label": "D", "text": "புலவனைப் பாடுதல்"}], "correct_answer": "B", "marks": 2, "subject": "tamil", "part": "A"},
    {"id": "tamil_21", "question_number": 21, "question_text": "குணங்குடி மஸ்தானின் இயற்பெயர் எது?", "options": [{"label": "A", "text": "ஷைகு முஸ்தபா"}, {"label": "B", "text": "முஸ்தபா ஷைகு"}, {"label": "C", "text": "குணங்குடி முஸ்தபா"}, {"label": "D", "text": "ஷைகு குணங்குடி"}], "correct_answer": "A", "marks": 1, "subject": "tamil", "part": "A"},
    {"id": "tamil_22", "question_number": 22, "question_text": "கட்டடக் கலை மிகவும் சிறப்பு பெற்றிருந்த காலம்?", "options": [{"label": "A", "text": "சோழர் காலம்"}, {"label": "B", "text": "பல்லவர் காலம்"}, {"label": "C", "text": "பாண்டியர் காலம்"}, {"label": "D", "text": "சேரர் காலம்"}], "correct_answer": "B", "marks": 1, "subject": "tamil", "part": "A"},
    {"id": "tamil_23", "question_number": 23, "question_text": "குழல் கேட்டு மகிழ்ந்தான் - இது எவ்வகை ஆகுபெயர்?", "options": [{"label": "A", "text": "கருவி ஆகுபெயர்"}, {"label": "B", "text": "தொழில் ஆகுபெயர்"}, {"label": "C", "text": "காரண ஆகுபெயர்"}, {"label": "D", "text": "பண்பு ஆகுபெயர்"}], "correct_answer": "A", "marks": 1, "subject": "tamil", "part": "A"},
    {"id": "tamil_24", "question_number": 24, "question_text": "'செங்கோல்' என்பதன் எதிர்ச்சொல் எது?", "options": [{"label": "A", "text": "வளை கோல்"}, {"label": "B", "text": "நேர் கோல்"}, {"label": "C", "text": "கொடுங்கோல்"}, {"label": "D", "text": "வெண் கோல்"}], "correct_answer": "C", "marks": 1, "subject": "tamil", "part": "A"},
    {"id": "tamil_25", "question_number": 25, "question_text": "இரங்கல் இரங்கல் நிமித்தம் - இவற்றுக்கு உரிய திணை?", "options": [{"label": "A", "text": "பெருந்திணை"}, {"label": "B", "text": "கரந்தை"}, {"label": "C", "text": "காஞ்சி"}, {"label": "D", "text": "வாகை"}], "correct_answer": "B", "marks": 1, "subject": "tamil", "part": "A"},
    {"id": "tamil_26", "question_number": 26, "question_text": "மண நூல் என வழங்கப்படுவது?", "options": [{"label": "A", "text": "மணிமேகலை"}, {"label": "B", "text": "சீவக சிந்தாமணி"}, {"label": "C", "text": "குண்டலகேசி"}, {"label": "D", "text": "சிலப்பதிகாரம்"}], "correct_answer": "B", "marks": 1, "subject": "tamil", "part": "A"},
    {"id": "tamil_27", "question_number": 27, "question_text": "17 நரம்புகளைக் கொண்ட யாழின் பெயர் என்ன?", "options": [{"label": "A", "text": "மகர யாழ்"}, {"label": "B", "text": "பேர் யாழ்"}, {"label": "C", "text": "சிறு யாழ்"}, {"label": "D", "text": "வீணை யாழ்"}], "correct_answer": "A", "marks": 1, "subject": "tamil", "part": "A"},
    {"id": "tamil_28", "question_number": 28, "question_text": "கொற்கையின் அரசராகவும் புலவராகவும் இருந்தவர் யார்?", "options": [{"label": "A", "text": "இராசராச சோழன்"}, {"label": "B", "text": "அதிவீரராம பாண்டியன்"}, {"label": "C", "text": "கரிகாலன்"}, {"label": "D", "text": "நெடுஞ்செழியன்"}], "correct_answer": "B", "marks": 1, "subject": "tamil", "part": "A"},
    {"id": "tamil_29", "question_number": 29, "question_text": "எதிர்கால இடைநிலைகள் என்ன?", "options": [{"label": "A", "text": "ப், வ்"}, {"label": "B", "text": "க், ச்"}, {"label": "C", "text": "த், ந்"}, {"label": "D", "text": "ம், ய்"}], "correct_answer": "A", "marks": 1, "subject": "tamil", "part": "A"},
    {"id": "tamil_30", "question_number": 30, "question_text": "உடம்படு மெய் எனப்படும் இரு மெய்கள்?", "options": [{"label": "A", "text": "க், ச்"}, {"label": "B", "text": "ய், வ்"}, {"label": "C", "text": "ம், ந்"}, {"label": "D", "text": "த், ப்"}], "correct_answer": "B", "marks": 1, "subject": "tamil", "part": "A"}
]

# Shortened physics questions for brevity - you have 100 questions, I'll include first 20 and structure for rest
physics_questions = [
    {"id": "physics_1", "question_number": 1, "question_text": "A physical system is described by the constraint equation x² + y² ≥ a². Which of the following correctly classifies this constraint?", "options": [{"label": "A", "text": "Holonomic"}, {"label": "B", "text": "Non-holonomic"}, {"label": "C", "text": "Scleronomic"}, {"label": "D", "text": "Rheonomic"}], "correct_answer": "B", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_2", "question_number": 2, "question_text": "If a particle moves under a central force derived from a potential of the form V(r) = krⁿ⁺¹, then for the motion to be a central-force problem, which of the following is the correct condition on n?", "options": [{"label": "A", "text": "n > 2"}, {"label": "B", "text": "n > 3"}, {"label": "C", "text": "n > 4"}, {"label": "D", "text": "n > -3"}], "correct_answer": "D", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_3", "question_number": 3, "question_text": "A rigid body is rotating about a fixed axis in space. What is the number of degrees of freedom of the body?", "options": [{"label": "A", "text": "1"}, {"label": "B", "text": "2"}, {"label": "C", "text": "3"}, {"label": "D", "text": "4"}], "correct_answer": "A", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_4", "question_number": 4, "question_text": "Moment of inertia is", "options": [{"label": "A", "text": "a scalar"}, {"label": "B", "text": "a vector"}, {"label": "C", "text": "a tensor of rank two"}, {"label": "D", "text": "a tensor of higher rank"}], "correct_answer": "C", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_5", "question_number": 5, "question_text": "The Poisson bracket of a dynamical function f with the Hamiltonian H is given by {f, H} = 0. What does this condition signify?", "options": [{"label": "A", "text": "The function varies with time"}, {"label": "B", "text": "The function is a constant of motion"}, {"label": "C", "text": "The function is a quadratic function of time"}, {"label": "D", "text": "The function is zero"}], "correct_answer": "B", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_6", "question_number": 6, "question_text": "Which of the following is a non-fictitious force?", "options": [{"label": "A", "text": "Coriolis force"}, {"label": "B", "text": "Centrifugal force"}, {"label": "C", "text": "Nuclear force"}, {"label": "D", "text": "Euler force"}], "correct_answer": "C", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_7", "question_number": 7, "question_text": "Which of the following represents the correct expression for the relativistic force?", "options": [{"label": "A", "text": "F = m₀ dv/dt (1 - v²/c²)⁻³/²"}, {"label": "B", "text": "F = m₀ dv/dt (1 - v²/c²)³/²"}, {"label": "C", "text": "F = m₀ dv/dt (1 - v²/c²)⁻¹/²"}, {"label": "D", "text": "F = m₀ dv/dt (1 - v²/c²)¹/²"}], "correct_answer": "C", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_8", "question_number": 8, "question_text": "The moment of inertia of a solid disk about an axis tangent to the disk and lying in its plane is", "options": [{"label": "A", "text": "½ MR²"}, {"label": "B", "text": "¼ MR²"}, {"label": "C", "text": "⅝ MR²"}, {"label": "D", "text": "¾ MR²"}], "correct_answer": "D", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_9", "question_number": 9, "question_text": "A body moves under the influence of a central potential and has total energy E > 0. Which of the following statements is correct?", "options": [{"label": "A", "text": "It has two turning points"}, {"label": "B", "text": "It has one turning point"}, {"label": "C", "text": "It has three turning points"}, {"label": "D", "text": "It has four turning points"}], "correct_answer": "A", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_10", "question_number": 10, "question_text": "Two events occur simultaneously in an inertial frame S at positions x₁ and x₂. If the same events are observed from another inertial frame S' moving with velocity v, the time difference is", "options": [{"label": "A", "text": "Δt' = -v Δx / (c²√(1 - v²/c²))"}, {"label": "B", "text": "Δt' = v Δx / (c²√(1 - v²/c²))"}, {"label": "C", "text": "Δt' = v Δx / c²"}, {"label": "D", "text": "Δt' = -v Δx / c²"}], "correct_answer": "B", "marks": 1.5, "subject": "physics", "part": "B"}
]

# Continue with remaining physics questions (11-100)
remaining_physics = [
    {"id": "physics_11", "question_number": 11, "question_text": "For a continuous variable x, the probability density function is given by f(x) = kxe⁻ˣ/λ for x > 0. The expected (mean) value of x is", "options": [{"label": "A", "text": "λ"}, {"label": "B", "text": "2λ"}, {"label": "C", "text": "λ/2"}, {"label": "D", "text": "0"}], "correct_answer": "B", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_12", "question_number": 12, "question_text": "Determine the Laplace transform of e⁻²ᵗ sin(4t).", "options": [{"label": "A", "text": "4 / ((s+2)² + 16)"}, {"label": "B", "text": "4 / (s² + 4s + 20)"}, {"label": "C", "text": "4s / (s² + 4s + 20)"}, {"label": "D", "text": "4s / (2s² + 4s + 20)"}], "correct_answer": "B", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_13", "question_number": 13, "question_text": "Evaluate the contour integral I = ∮ (sin z / (z² - π²)) dz, where C denotes the circle |z| = 2.", "options": [{"label": "A", "text": "0"}, {"label": "B", "text": "2πi"}, {"label": "C", "text": "πi"}, {"label": "D", "text": "-πi"}], "correct_answer": "B", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_14", "question_number": 14, "question_text": "Let pₙ(x) denote a polynomial of degree n with real coefficients defined on the interval 2 ≤ x ≤ 4. If ∫⁴₂ pₙ(x) pₘ(x) dx = δₙₘ, then the first two normalized functions p₀(x) and p₁(x) are", "options": [{"label": "A", "text": "p₀(x) = 1/√2, p₁(x) = √3/2 (-3 - x)"}, {"label": "B", "text": "p₀(x) = 1/√2, p₁(x) = √3/2 (3 + x)"}, {"label": "C", "text": "p₀(x) = 1/2, p₁(x) = 1/√3(3 - x)"}, {"label": "D", "text": "p₀(x) = 1/√2, p₁(x) = 1/√2 (3 - x)"}], "correct_answer": "D", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_15", "question_number": 15, "question_text": "For the vector field Ā = yzî + xz ĵ + xy k̂, the line integral around a rectangular loop C, bounded by x = 0, x = a and y = 0, y = b, is", "options": [{"label": "A", "text": "π(a³ + b³)"}, {"label": "B", "text": "π(ab² + a²b)"}, {"label": "C", "text": "ab"}, {"label": "D", "text": "0"}], "correct_answer": "D", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_16", "question_number": 16, "question_text": "Which one of the following cannot represent the real part of an analytic function of z = x + iy?", "options": [{"label": "A", "text": "x²y"}, {"label": "B", "text": "x² - y²"}, {"label": "C", "text": "x³ - 3xy²"}, {"label": "D", "text": "3x²y - y³"}], "correct_answer": "A", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_17", "question_number": 17, "question_text": "The Fourier transform of the derivative of the delta function δ'(x) is proportional to", "options": [{"label": "A", "text": "0"}, {"label": "B", "text": "1"}, {"label": "C", "text": "sin k"}, {"label": "D", "text": "ik"}], "correct_answer": "D", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_18", "question_number": 18, "question_text": "If a conservative force F originates from a potential V(r), where r is the distance from the origin, then it follows that", "options": [{"label": "A", "text": "∇ × F = 0"}, {"label": "B", "text": "∇ · F = 0"}, {"label": "C", "text": "∇V = 0"}, {"label": "D", "text": "∇²V = 0"}], "correct_answer": "A", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_19", "question_number": 19, "question_text": "Find the unit normal to the surface x² + y² - z = 1 at the point (1, 1, 1).", "options": [{"label": "A", "text": "(î + ĵ - k̂) / √3"}, {"label": "B", "text": "(2î + ĵ - k̂) / √6"}, {"label": "C", "text": "(î + 2ĵ - k̂) / √6"}, {"label": "D", "text": "(2î + 2ĵ – k̂) / 3"}], "correct_answer": "D", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_20", "question_number": 20, "question_text": "Which of the following represents a function analytic everywhere in the complex plane?", "options": [{"label": "A", "text": "z²"}, {"label": "B", "text": "(z*)²"}, {"label": "C", "text": "|z|²"}, {"label": "D", "text": "√z"}], "correct_answer": "A", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_21", "question_number": 21, "question_text": "Find the value of [Â, ĈB] + B[Â, Ĉ].", "options": [{"label": "A", "text": "[Â, B]Ĉ + B[Â, Ĉ]"}, {"label": "B", "text": "[Â, B][Â, Ĉ]"}, {"label": "C", "text": "Â[B, Ĉ] + [Â, B][Â, Ĉ]"}, {"label": "D", "text": "[B, ÂĈ] + B[Ĉ, Â]"}], "correct_answer": "A", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_22", "question_number": 22, "question_text": "Two state vectors are given. Find the inner product (Φ|Ψ).", "options": [{"label": "A", "text": "4 + 6i"}, {"label": "B", "text": "10i"}, {"label": "C", "text": "2 - 5i"}, {"label": "D", "text": "-8 + 4i"}], "correct_answer": "B", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_23", "question_number": 23, "question_text": "The Triangle Inequality and Schwarz Inequality are valid for which of the following?", "options": [{"label": "A", "text": "Orthonormal set of eigenvectors"}, {"label": "B", "text": "Dependent set of state vectors"}, {"label": "C", "text": "Independent set of state vectors"}, {"label": "D", "text": "Mutually exclusive physical states"}], "correct_answer": "C", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_24", "question_number": 24, "question_text": "If the eigenvalue of an operator A corresponding to a state vector |ψ⟩ is a, then the eigenvalue of the inverse operator A⁻¹ is", "options": [{"label": "A", "text": "a"}, {"label": "B", "text": "a²"}, {"label": "C", "text": "1/a"}, {"label": "D", "text": "-a"}], "correct_answer": "C", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_25", "question_number": 25, "question_text": "The ground-state energy of five identical spin-½ fermions confined in a one-dimensional harmonic oscillator of frequency ω is", "options": [{"label": "A", "text": "½ ħω"}, {"label": "B", "text": "⁵⁄₂ ħω"}, {"label": "C", "text": "⁷⁄₂ ħω"}, {"label": "D", "text": "5ħω"}], "correct_answer": "C", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_26", "question_number": 26, "question_text": "The wavefunction of a particle is given by ψ = 1/√2 (φ₀ + iφ₁). The expectation value of the Hamiltonian in the state ψ is", "options": [{"label": "A", "text": "(E₀ + E₁) / 2"}, {"label": "B", "text": "(E₀ - E₁) / 2"}, {"label": "C", "text": "(E₀ - 2E₁) / 3"}, {"label": "D", "text": "(E₀ + E₁) / 2"}], "correct_answer": "A", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_27", "question_number": 27, "question_text": "For a perturbation H' = ax, the first-order correction to the ground-state energy of an infinite square-well is", "options": [{"label": "A", "text": "απ/2"}, {"label": "B", "text": "απ"}, {"label": "C", "text": "απ/4"}, {"label": "D", "text": "απ/√2"}], "correct_answer": "A", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_28", "question_number": 28, "question_text": "The energy of the first excited level of a particle moving in the two-dimensional harmonic potential V(x, y) = ½ mω²(x² + 4y²) is", "options": [{"label": "A", "text": "2ħω"}, {"label": "B", "text": "3ħω"}, {"label": "C", "text": "4ħω"}, {"label": "D", "text": "ħω"}], "correct_answer": "B", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_29", "question_number": 29, "question_text": "For angular-momentum operators Lₓ, Lᵧ, Lz, the commutator [Lₓ, LᵧLz] is equal to", "options": [{"label": "A", "text": "iħ(Lᵧ² + Lz²)"}, {"label": "B", "text": "2iħLz"}, {"label": "C", "text": "iħ(Lᵧ² - Lz²)"}, {"label": "D", "text": "0"}], "correct_answer": "C", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_30", "question_number": 30, "question_text": "A spin-½ particle is in the quantum state |ψ⟩ = 1/√6 (1 + i, 2)ᵀ. If Sₓ is measured, the probability of obtaining +ħ/2 is", "options": [{"label": "A", "text": "1/3"}, {"label": "B", "text": "2/3"}, {"label": "C", "text": "5/6"}, {"label": "D", "text": "1/6"}], "correct_answer": "C", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_31", "question_number": 31, "question_text": "A magnetic field B = B₀(î + 2ĵ – 4k̂) exists in space. If a charged particle moves with velocity v = v₀(3î – ĵ + 2k̂) and experiences zero net force, the electric field must be", "options": [{"label": "A", "text": "E = −v₀B₀(3î – 2ĵ – 4k̂)"}, {"label": "B", "text": "E = −v₀B₀(î + ĵ + 7k̂)"}, {"label": "C", "text": "E = v₀B₀(14î + 7k̂)"}, {"label": "D", "text": "E = −v₀B₀(14î + 7k̂)"}], "correct_answer": "D", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_32", "question_number": 32, "question_text": "A circular conducting ring of radius R rotates with constant angular velocity ω about its diameter along the x-axis. A uniform magnetic field B is applied along the y-axis. The emf induced at time t > 0 is", "options": [{"label": "A", "text": "Bω²πR²t"}, {"label": "B", "text": "BωR² tan(ωt)"}, {"label": "C", "text": "BωπR² sin(ωt)"}, {"label": "D", "text": "BωπR² cos(ωt)"}], "correct_answer": "D", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_33", "question_number": 33, "question_text": "A spherically symmetric charge distribution is given by ρ(r) = Ar⁻²e⁻ᵏʳ. The electrostatic potential V(r) varies as", "options": [{"label": "A", "text": "re⁻ᵏʳ"}, {"label": "B", "text": "(1/r)e⁻ᵏʳ"}, {"label": "C", "text": "e⁻ᵏʳ"}, {"label": "D", "text": "(1/r)(1 - e⁻ᵏʳ)"}], "correct_answer": "B", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_34", "question_number": 34, "question_text": "The magnetic field for the TE₁₁ mode in a rectangular waveguide is Hz = H₀ cos(0.3πx) cos(0.4πy). The dimensions are", "options": [{"label": "A", "text": "a = 3.33 cm, b = 2.50 cm"}, {"label": "B", "text": "a = 0.40 cm, b = 0.30 cm"}, {"label": "C", "text": "a = 0.80 cm, b = 0.60 cm"}, {"label": "D", "text": "a = 1.66 cm, b = 1.25 cm"}], "correct_answer": "A", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_35", "question_number": 35, "question_text": "The time-averaged energy density of a linearly polarized electromagnetic wave in free space is", "options": [{"label": "A", "text": "½ ε₀E₀²"}, {"label": "B", "text": "¼ ε₀E₀²"}, {"label": "C", "text": "ε₀E₀²"}, {"label": "D", "text": "2ε₀E₀²"}], "correct_answer": "A", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_36", "question_number": 36, "question_text": "Which one of the following quantities is Lorentz invariant?", "options": [{"label": "A", "text": "|E × B|²"}, {"label": "B", "text": "|E|² – |B|²"}, {"label": "C", "text": "|E|² + |B|²"}, {"label": "D", "text": "|E|²|B|²"}], "correct_answer": "B", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_37", "question_number": 37, "question_text": "If a force F originates from a scalar potential V(r), then", "options": [{"label": "A", "text": "∇ × F = 0"}, {"label": "B", "text": "∇ · F = 0"}, {"label": "C", "text": "∇V = 0"}, {"label": "D", "text": "∇²V = 0"}], "correct_answer": "A", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_38", "question_number": 38, "question_text": "A magnetic dipole with moment m is placed in a non-uniform magnetic field B. The torque acting on the dipole about the origin is", "options": [{"label": "A", "text": "r × (m × B)"}, {"label": "B", "text": "r × ∇(m · B)"}, {"label": "C", "text": "m × B"}, {"label": "D", "text": "m × B + r × ∇(m · B)"}], "correct_answer": "C", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_39", "question_number": 39, "question_text": "A cube has a constant electric potential V on its surface. If there are no charges within the cube, the potential at its center is", "options": [{"label": "A", "text": "V"}, {"label": "B", "text": "V/8"}, {"label": "C", "text": "0"}, {"label": "D", "text": "V/6"}], "correct_answer": "A", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_40", "question_number": 40, "question_text": "The self-inductance per unit length of a long solenoid of radius R and n turns per unit length is", "options": [{"label": "A", "text": "µ₀πR²n²"}, {"label": "B", "text": "2µ₀πR²n"}, {"label": "C", "text": "2µ₀R²n²"}, {"label": "D", "text": "µ₀πR²n"}], "correct_answer": "A", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_41", "question_number": 41, "question_text": "Consider the phase transition of liquid water into steam at 100°C and 1 atm. Which quantity remains continuous during the transition?", "options": [{"label": "A", "text": "Gibbs free energy"}, {"label": "B", "text": "Internal energy"}, {"label": "C", "text": "Entropy"}, {"label": "D", "text": "Specific volume"}], "correct_answer": "A", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_42", "question_number": 42, "question_text": "The internal energy is E = bS³/(V²N). The temperature is equal to", "options": [{"label": "A", "text": "bS²/(VN)"}, {"label": "B", "text": "3bS²/(V²N)"}, {"label": "C", "text": "bS³/(V²N)"}, {"label": "D", "text": "(bS²/(VN))²"}], "correct_answer": "B", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_43", "question_number": 43, "question_text": "The pressure P of a non-relativistic Fermi gas in three dimensions, at T = 0, depends on the particle number density n as", "options": [{"label": "A", "text": "n⁵/³"}, {"label": "B", "text": "n¹/³"}, {"label": "C", "text": "n²/³"}, {"label": "D", "text": "n⁴/³"}], "correct_answer": "A", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_44", "question_number": 44, "question_text": "For a diatomic ideal gas near room temperature, what fraction of heat supplied is used for external work during isobaric expansion?", "options": [{"label": "A", "text": "1/7"}, {"label": "B", "text": "2/7"}, {"label": "C", "text": "3/7"}, {"label": "D", "text": "2/5"}], "correct_answer": "D", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_45", "question_number": 45, "question_text": "If the mean-square energy fluctuations vary as Tᵃ, then the total energy varies as", "options": [{"label": "A", "text": "Tᵃ⁻²"}, {"label": "B", "text": "Tᵃ/²"}, {"label": "C", "text": "Tᵃ⁻¹"}, {"label": "D", "text": "Tᵃ"}], "correct_answer": "C", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_46", "question_number": 46, "question_text": "N classical, non-interacting point particles move on a two-dimensional sphere surface. The total internal energy is", "options": [{"label": "A", "text": "½ NkT"}, {"label": "B", "text": "NkT"}, {"label": "C", "text": "³⁄₂ NkT"}, {"label": "D", "text": "2NkT"}], "correct_answer": "B", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_47", "question_number": 47, "question_text": "A system of N non-interacting and distinguishable particles, each of spin-1. The entropy is", "options": [{"label": "A", "text": "2k ln N"}, {"label": "B", "text": "3k ln N"}, {"label": "C", "text": "Nk ln 2"}, {"label": "D", "text": "Nk ln 3"}], "correct_answer": "D", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_48", "question_number": 48, "question_text": "In a Bose-Einstein condensate, the particles", "options": [{"label": "A", "text": "exhibit strong inter-particle attraction"}, {"label": "B", "text": "condense in real space"}, {"label": "C", "text": "have overlapping wavefunctions"}, {"label": "D", "text": "possess a large, positive chemical potential"}], "correct_answer": "C", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_49", "question_number": 49, "question_text": "In black-body radiation within a cavity, photons are continuously created and absorbed because", "options": [{"label": "A", "text": "the chemical potential of photons is zero"}, {"label": "B", "text": "photons obey the Pauli exclusion principle"}, {"label": "C", "text": "photons are spin-1 bosons"}, {"label": "D", "text": "the entropy of photons is very large"}], "correct_answer": "A", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_50", "question_number": 50, "question_text": "A reversible Carnot engine operates between temperatures T₁ and T₂ (T₂ > T₁) using a photon gas. The efficiency is", "options": [{"label": "A", "text": "1 - 3T₁/(4T₂)"}, {"label": "B", "text": "1 - T₁/T₂"}, {"label": "C", "text": "1 - (T₁/T₂)³/⁴"}, {"label": "D", "text": "1 - (T₁/T₂)⁴/³"}], "correct_answer": "B", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_51", "question_number": 51, "question_text": "A 10 kHz signal is digitized. Which sampling time is suitable for accurate digitization?", "options": [{"label": "A", "text": "100 µs"}, {"label": "B", "text": "40 µs"}, {"label": "C", "text": "60 µs"}, {"label": "D", "text": "200 µs"}], "correct_answer": "B", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_52", "question_number": 52, "question_text": "A 12-bit ADC with 1 V reference voltage has a resolution of approximately", "options": [{"label": "A", "text": "0.24 V"}, {"label": "B", "text": "0.24 mV"}, {"label": "C", "text": "0.24 µV"}, {"label": "D", "text": "0.24 nV"}], "correct_answer": "B", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_53", "question_number": 53, "question_text": "In a common-emitter transistor amplifier, which statement is true?", "options": [{"label": "A", "text": "Output is taken from the emitter"}, {"label": "B", "text": "Output has 180° phase shift"}, {"label": "C", "text": "No phase difference between signals"}, {"label": "D", "text": "Both p-n junctions are forward biased"}], "correct_answer": "B", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_54", "question_number": 54, "question_text": "A full-wave rectifier with 10 V peak output has DC output voltage of approximately", "options": [{"label": "A", "text": "10.0 V"}, {"label": "B", "text": "7.07 V"}, {"label": "C", "text": "6.36 V"}, {"label": "D", "text": "3.18 V"}], "correct_answer": "C", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_55", "question_number": 55, "question_text": "For a 6-bit ADC with 32 µs conversion time, the required clock frequency is approximately", "options": [{"label": "A", "text": "1 MHz"}, {"label": "B", "text": "2 MHz"}, {"label": "C", "text": "0.5 MHz"}, {"label": "D", "text": "4 MHz"}], "correct_answer": "C", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_56", "question_number": 56, "question_text": "An 8-bit successive-approximation ADC's analog input increases from 1.0 V to 2.0 V. The conversion time", "options": [{"label": "A", "text": "Remains the same"}, {"label": "B", "text": "Doubles"}, {"label": "C", "text": "Reduces to half"}, {"label": "D", "text": "Increases fourfold"}], "correct_answer": "A", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_57", "question_number": 57, "question_text": "An RC phase-shift network produces 30°. How many RC sections are needed for oscillation?", "options": [{"label": "A", "text": "6"}, {"label": "B", "text": "12"}, {"label": "C", "text": "9"}, {"label": "D", "text": "3"}], "correct_answer": "A", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_58", "question_number": 58, "question_text": "Which logic expression does NOT represent XOR for inputs A and B?", "options": [{"label": "A", "text": "(A + B)A̅B̅"}, {"label": "B", "text": "A̅B + AB̅"}, {"label": "C", "text": "(A+B)(A̅ + B̅)"}, {"label": "D", "text": "(A + B)AB"}], "correct_answer": "D", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_59", "question_number": 59, "question_text": "The minimum number of NAND gates required to construct an OR gate is", "options": [{"label": "A", "text": "2"}, {"label": "B", "text": "4"}, {"label": "C", "text": "5"}, {"label": "D", "text": "3"}], "correct_answer": "D", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_60", "question_number": 60, "question_text": "An LED operates at 1.5 V and 5 mA with 80% efficiency. Photons emitted per second is approximately", "options": [{"label": "A", "text": "5.0 × 10¹⁶"}, {"label": "B", "text": "1.5 × 10¹⁶"}, {"label": "C", "text": "0.8 × 10¹⁶"}, {"label": "D", "text": "2.5 × 10¹⁶"}], "correct_answer": "D", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_61", "question_number": 61, "question_text": "For energy band E = ħ²k(2k - 3)/(2m), the effective mass is", "options": [{"label": "A", "text": "m"}, {"label": "B", "text": "2m/3"}, {"label": "C", "text": "m/3"}, {"label": "D", "text": "2m"}], "correct_answer": "C", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_62", "question_number": 62, "question_text": "1 Å X-rays on simple cubic crystal give first-order Bragg reflection from (311) at 30°. Lattice parameter is approximately", "options": [{"label": "A", "text": "1 Å"}, {"label": "B", "text": "√3 Å"}, {"label": "C", "text": "√11/2 Å"}, {"label": "D", "text": "√11 Å"}], "correct_answer": "D", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_63", "question_number": 63, "question_text": "For simple cubic a = 2.65 Å, λ = 1.53 Å, first-order diffraction from (111) occurs at θ approximately", "options": [{"label": "A", "text": "15°"}, {"label": "B", "text": "30°"}, {"label": "C", "text": "45°"}, {"label": "D", "text": "60°"}], "correct_answer": "B", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_64", "question_number": 64, "question_text": "Miller indices of a plane containing [100], [011], and [111] are", "options": [{"label": "A", "text": "(011)"}, {"label": "B", "text": "(101)"}, {"label": "C", "text": "(100)"}, {"label": "D", "text": "(110)"}], "correct_answer": "A", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_65", "question_number": 65, "question_text": "For ideal fermion gas at T = 0 K, if density and mass are doubled, average energy per particle is multiplied by", "options": [{"label": "A", "text": "2¹/²"}, {"label": "B", "text": "1"}, {"label": "C", "text": "2¹/³"}, {"label": "D", "text": "2⁻¹/³"}], "correct_answer": "D", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_66", "question_number": 66, "question_text": "Valence electrons of a metal primarily determine which property?", "options": [{"label": "A", "text": "Electrical conductivity"}, {"label": "B", "text": "Thermal conductivity"}, {"label": "C", "text": "Shear modulus"}, {"label": "D", "text": "Metallic luster"}], "correct_answer": "C", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_67", "question_number": 67, "question_text": "For 2D free electron gas, n and Fermi energy E_F are related as", "options": [{"label": "A", "text": "n = (2mE_F)³/² / (3π²ħ³)"}, {"label": "B", "text": "n = mE_F / (πħ²)"}, {"label": "C", "text": "n = mE_F / (2πħ²)"}, {"label": "D", "text": "n = 2¹/³(mE_F)¹/³ / (πħ)"}], "correct_answer": "B", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_68", "question_number": 68, "question_text": "Which cannot be explained by harmonic approximation for lattice vibrations?", "options": [{"label": "A", "text": "Debye's T³ law"}, {"label": "B", "text": "Dulong-Petit's law"}, {"label": "C", "text": "Optical branches"}, {"label": "D", "text": "Thermal expansion"}], "correct_answer": "D", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_69", "question_number": 69, "question_text": "A solid has temperature-independent susceptibility χ = C. Which statement is correct?", "options": [{"label": "A", "text": "If C > 0, material is diamagnetic"}, {"label": "B", "text": "If C > 0, material is ferromagnetic"}, {"label": "C", "text": "If C < 0, could be type-I superconductor"}, {"label": "D", "text": "If C > 0, could be type-II superconductor"}], "correct_answer": "B", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_70", "question_number": 70, "question_text": "For 1D crystal with weak periodic potential U(x) = U₀ cos(2πx/a), energy gap at k = π/a is approximately", "options": [{"label": "A", "text": "U₀"}, {"label": "B", "text": "U₀/2"}, {"label": "C", "text": "2U₀"}, {"label": "D", "text": "U₀/4"}], "correct_answer": "C", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_71", "question_number": 71, "question_text": "Potential energy V(r) = -a/r⁶ + b/r¹². The potential at equilibrium separation is", "options": [{"label": "A", "text": "-4a²/b"}, {"label": "B", "text": "-2a²/b"}, {"label": "C", "text": "-a²/2b"}, {"label": "D", "text": "-a²/4b"}], "correct_answer": "D", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_72", "question_number": 72, "question_text": "For 2D system with E = ħuk, density of states D(E) dependence is", "options": [{"label": "A", "text": "1/√E"}, {"label": "B", "text": "√E"}, {"label": "C", "text": "E"}, {"label": "D", "text": "constant"}], "correct_answer": "C", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_73", "question_number": 73, "question_text": "Relative magnetic permeability of type-I superconductor is", "options": [{"label": "A", "text": "0"}, {"label": "B", "text": "-1"}, {"label": "C", "text": "2π"}, {"label": "D", "text": "1/(4π)"}], "correct_answer": "A", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_74", "question_number": 74, "question_text": "Black body at 1000 K has maximum intensity in which region?", "options": [{"label": "A", "text": "Visible"}, {"label": "B", "text": "Infrared"}, {"label": "C", "text": "Ultraviolet"}, {"label": "D", "text": "Microwave"}], "correct_answer": "B", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_75", "question_number": 75, "question_text": "Hydrogen atom in ground state collides with 13.377 eV electron. Maximum radius increase factor is", "options": [{"label": "A", "text": "7"}, {"label": "B", "text": "8"}, {"label": "C", "text": "49"}, {"label": "D", "text": "64"}], "correct_answer": "C", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_76", "question_number": 76, "question_text": "Interaction between neutral atom and ion at large separation has potential", "options": [{"label": "A", "text": "V ∝ 1/r²"}, {"label": "B", "text": "V ∝ -1/r"}, {"label": "C", "text": "V ∝ -e⁻ʳ/ᵃ / r"}, {"label": "D", "text": "V ∝ -1/r³"}], "correct_answer": "A", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_77", "question_number": 77, "question_text": "Excited state lifetime is 1 ns. Natural linewidth is of the order of", "options": [{"label": "A", "text": "10⁻¹⁰ eV"}, {"label": "B", "text": "10⁻⁹ eV"}, {"label": "C", "text": "10⁻⁶ eV"}, {"label": "D", "text": "10⁻⁴ eV"}], "correct_answer": "C", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_78", "question_number": 78, "question_text": "Number of distinct spectral components in normal Zeeman effect is", "options": [{"label": "A", "text": "2"}, {"label": "B", "text": "3"}, {"label": "C", "text": "4"}, {"label": "D", "text": "6"}], "correct_answer": "B", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_79", "question_number": 79, "question_text": "If electron had spin ½ (instead of ½), for Z = 5, configuration would be", "options": [{"label": "A", "text": "1s⁴ 2s¹"}, {"label": "B", "text": "1s⁴ 2s² 2p¹"}, {"label": "C", "text": "1s⁵"}, {"label": "D", "text": "1s³ 2s¹ 2p¹"}], "correct_answer": "A", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_80", "question_number": 80, "question_text": "In two-level system, population inversion cannot be achieved using optical pumping because", "options": [{"label": "A", "text": "Upward and downward rates are equal"}, {"label": "B", "text": "Upward transitions are forbidden"}, {"label": "C", "text": "Downward transitions are forbidden"}, {"label": "D", "text": "Spontaneous decay is negligible"}], "correct_answer": "A", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_81", "question_number": 81, "question_text": "Ground state of ¹¹Na is ²S₁/₂. In weak field B, energy level separation is", "options": [{"label": "A", "text": "μ_BB"}, {"label": "B", "text": "2μ_BB"}, {"label": "C", "text": "4μ_BB"}, {"label": "D", "text": "6μ_BB"}], "correct_answer": "B", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_82", "question_number": 82, "question_text": "Black body spectrum peaks in visible at approximately", "options": [{"label": "A", "text": "1000 K"}, {"label": "B", "text": "5000 K"}, {"label": "C", "text": "10000 K"}, {"label": "D", "text": "500 K"}], "correct_answer": "B", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_83", "question_number": 83, "question_text": "Fundamental quark process for neutron β-decay is", "options": [{"label": "A", "text": "d → u + e⁻ + ν̄ₑ"}, {"label": "B", "text": "d → u + e⁻"}, {"label": "C", "text": "s → u + e⁻ + ν̄ₑ"}, {"label": "D", "text": "u → d + e⁻ + ν̄ₑ"}], "correct_answer": "A", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_84", "question_number": 84, "question_text": "In nuclear shell model, predicted spin-parity of ¹⁵N is", "options": [{"label": "A", "text": "1/2⁻"}, {"label": "B", "text": "1/2⁺"}, {"label": "C", "text": "3/2⁻"}, {"label": "D", "text": "3/2⁺"}], "correct_answer": "A", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_85", "question_number": 85, "question_text": "Stable nucleus with one-third radius of ¹⁸⁹Os is", "options": [{"label": "A", "text": "⁷Li"}, {"label": "B", "text": "¹⁶O"}, {"label": "C", "text": "⁴He"}, {"label": "D", "text": "¹⁴N"}], "correct_answer": "A", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_86", "question_number": 86, "question_text": "Reaction e⁺ + e⁻ → γ is forbidden because", "options": [{"label": "A", "text": "Lepton number not conserved"}, {"label": "B", "text": "Linear momentum not conserved"}, {"label": "C", "text": "Angular momentum not conserved"}, {"label": "D", "text": "Charge not conserved"}], "correct_answer": "B", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_87", "question_number": 87, "question_text": "Deuteron wavefunction is s- and d-states superposition. Which is NOT true?", "options": [{"label": "A", "text": "Deuteron has nonzero quadrupole moment"}, {"label": "B", "text": "Neutron-proton potential is non-central"}, {"label": "C", "text": "Orbital wavefunction not spherically symmetric"}, {"label": "D", "text": "Hamiltonian fails to conserve angular momentum"}], "correct_answer": "D", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_88", "question_number": 88, "question_text": "Ground-state spin-parity of ¹⁷O in shell model is", "options": [{"label": "A", "text": "1/2⁻"}, {"label": "B", "text": "3/2⁻"}, {"label": "C", "text": "3/2⁺"}, {"label": "D", "text": "5/2⁺"}], "correct_answer": "D", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_89", "question_number": 89, "question_text": "Which set represents fundamental particles?", "options": [{"label": "A", "text": "Electron, photon, and neutrino"}, {"label": "B", "text": "Proton, electron, and photon"}, {"label": "C", "text": "Proton, electron, and neutron"}, {"label": "D", "text": "Quark, electron, and meson"}], "correct_answer": "A", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_90", "question_number": 90, "question_text": "Which reactions are forbidden for free particles?", "options": [{"label": "A", "text": "(ii) only"}, {"label": "B", "text": "(ii) and (iv)"}, {"label": "C", "text": "(i) and (iv)"}, {"label": "D", "text": "(i) and (ii)"}], "correct_answer": "D", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_91", "question_number": 91, "question_text": "Choose the correct statement", "options": [{"label": "A", "text": "Neutron interacts via electromagnetic force"}, {"label": "B", "text": "Electron doesn't participate in weak interactions"}, {"label": "C", "text": "Neutrino interacts through weak and EM forces"}, {"label": "D", "text": "Quark interacts via strong and weak forces"}], "correct_answer": "D", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_92", "question_number": 92, "question_text": "If charm quark has C = 1, modified Gell-Mann-Nishijima formula is", "options": [{"label": "A", "text": "Q = I₃ + ½(B - S – C)"}, {"label": "B", "text": "Q = I₃ + ½(B – S + C)"}, {"label": "C", "text": "Q = I₃ + ½(B + S – C)"}, {"label": "D", "text": "Q = I₃ + ½(B + S + C)"}], "correct_answer": "D", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_93", "question_number": 93, "question_text": "Resolving power of diffraction grating can be enhanced by", "options": [{"label": "A", "text": "Using first diffraction order"}, {"label": "B", "text": "Using larger grating spacing"}, {"label": "C", "text": "Covering portion of grating"}, {"label": "D", "text": "Illuminating maximum width"}], "correct_answer": "D", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_94", "question_number": 94, "question_text": "Thin air film of thickness d. Condition for constructive interference in reflected light is", "options": [{"label": "A", "text": "2d = (m - ½)λ"}, {"label": "B", "text": "2d = mλ"}, {"label": "C", "text": "2d = (m - 1)λ"}, {"label": "D", "text": "2λ = (m - 1)d"}], "correct_answer": "A", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_95", "question_number": 95, "question_text": "Isothermal compressibility κ_T = (1/V)(∂V/∂P)_T. For ideal gas, its value is", "options": [{"label": "A", "text": "1/P"}, {"label": "B", "text": "n/P"}, {"label": "C", "text": "1/nP"}, {"label": "D", "text": "-n/P"}], "correct_answer": "A", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_96", "question_number": 96, "question_text": "Young's double-slit: D = 50 cm, d = 0.1 cm, n = 1.5 mica shifts fringe by 0.2 cm. Thickness t is", "options": [{"label": "A", "text": "4 µm"}, {"label": "B", "text": "8 µm"}, {"label": "C", "text": "12 µm"}, {"label": "D", "text": "16 µm"}], "correct_answer": "B", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_97", "question_number": 97, "question_text": "Blackbody at temperature T has peak λ. If T increases to 4T, new wavelength is", "options": [{"label": "A", "text": "λ/256"}, {"label": "B", "text": "λ/64"}, {"label": "C", "text": "λ/16"}, {"label": "D", "text": "λ/4"}], "correct_answer": "D", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_98", "question_number": 98, "question_text": "Carnot engine absorbs heat from source at constant", "options": [{"label": "A", "text": "entropy"}, {"label": "B", "text": "pressure"}, {"label": "C", "text": "temperature"}, {"label": "D", "text": "volume"}], "correct_answer": "C", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_99", "question_number": 99, "question_text": "1D system of N particles with E = p²/2m + ½kx². Average internal energy at T is", "options": [{"label": "A", "text": "½ NkT"}, {"label": "B", "text": "³⁄₂ NkT"}, {"label": "C", "text": "3NkT"}, {"label": "D", "text": "NkT"}], "correct_answer": "D", "marks": 1.5, "subject": "physics", "part": "B"},
    {"id": "physics_100", "question_number": 100, "question_text": "For 3D polyatomic ideal gas with one vibrational mode excited, molar C_v is", "options": [{"label": "A", "text": "3R"}, {"label": "B", "text": "⁷⁄₂ R"}, {"label": "C", "text": "4R"}, {"label": "D", "text": "⁹⁄₂ R"}], "correct_answer": "C", "marks": 1.5, "subject": "physics", "part": "B"}
]

physics_questions.extend(remaining_physics)

async def seed_data():
    # Clear existing questions
    await db.questions.delete_many({})
    
    # Insert all questions
    all_questions = tamil_questions + physics_questions
    if all_questions:
        await db.questions.insert_many(all_questions)
    
    print(f"Seeded {len(tamil_questions)} Tamil questions")
    print(f"Seeded {len(physics_questions)} Physics questions")
    print(f"Total: {len(all_questions)} questions seeded successfully!")

if __name__ == "__main__":
    asyncio.run(seed_data())
    client.close()